set -e
Rscript template_function_QC_ProcessedInput_SO.R
mv Rplots.pdf QC_ProcessedInput_SO.pdf
Rscript template_function_ccbr1072_Environment.R
Rscript template_function_ccbr1072_SuppFig3.R
mv Rplots.pdf ccbr1072_SuppFig3.pdf
Rscript template_function_QC_CombNorm_SO.R
mv Rplots.pdf QC_CombNorm_SO.pdf
Rscript template_function_AllCells_CellTypes_SO.R
mv Rplots.pdf AllCells_CellTypes_SO.pdf
Rscript template_function_AllCells_ModScoreRBCProgs_CBGL.R
mv Rplots.pdf AllCells_ModScoreRBCProgs_CBGL.pdf
Rscript template_function_ccbr1072_SuppFig4a.R
mv Rplots.pdf ccbr1072_SuppFig4a.pdf
Rscript template_function_ccbr1072_SuppFig4b.R
mv Rplots.pdf ccbr1072_SuppFig4b.pdf
Rscript template_function_ccbr1072_SuppFig4c.R
mv Rplots.pdf ccbr1072_SuppFig4c.pdf
Rscript template_function_ccbr1072_SuppFig4d.R
mv Rplots.pdf ccbr1072_SuppFig4d.pdf
Rscript template_function_ccbr1072_SuppFig4e.R
mv Rplots.pdf ccbr1072_SuppFig4e.pdf
Rscript template_function_ccbr1072_SuppFig7a.R
mv Rplots.pdf ccbr1072_SuppFig7a.pdf
Rscript template_function_ccbr1072_SuppFig7b.R
mv Rplots.pdf ccbr1072_SuppFig7b.pdf
Rscript template_function_AllCellsCd34PosNeg_DualLabel_SO.R
mv Rplots.pdf AllCellsCd34PosNeg_DualLabel_SO.pdf
Rscript template_function_ccbr1072_Fig3a.R
mv Rplots.pdf ccbr1072_Fig3a.pdf
Rscript template_function_ccbr1072_Fig3b.R
mv Rplots.pdf ccbr1072_Fig3b.pdf
Rscript template_function_ccbr1072_SuppFig5.R
mv Rplots.pdf ccbr1072_SuppFig5.pdf
Rscript template_function_AllCellsTSP1KO_Filtered_SO.R
mv Rplots.pdf AllCellsTSP1KO_Filtered_SO.pdf
Rscript template_function_AllCellsWT_Filtered_SO_20240326.R
mv Rplots.pdf AllCellsWT_Filtered_SO_20240326.pdf
Rscript template_function_R02C10_Filtered_SO.R
mv Rplots.pdf R02C10_Filtered_SO.pdf
Rscript template_function_R02C11_Filtered_SO.R
mv Rplots.pdf R02C11_Filtered_SO.pdf
Rscript template_function_R04C12_Filtered_SO.R
mv Rplots.pdf R02C11_Filtered_SO.pdf
Rscript template_function_R04C12andC14_Filtered_SO.R
mv Rplots.pdf R04C12andC14_Filtered_SO.pdf
Rscript template_function_R04C14_Filtered_SO.R
mv Rplots.pdf template_function_R04C14_Filtered_SO.pdf
Rscript template_function_ccbr1072_Fig4a.R
mv Rplots.pdf ccbr1072_Fig4a.pdf
Rscript template_function_ccbr1072_Fig4b.R
mv Rplots.pdf ccbr1072_Fig4b.pdf
Rscript template_function_ccbr1072_Fig4c.R
mv Rplots.pdf ccbr1072_Fig4c.pdf
Rscript template_function_ccbr1072_Fig4d.R
mv Rplots.pdf ccbr1072_Fig4d.pdf
Rscript template_function_ccbr1072_Fig6a.R
mv Rplots.pdf ccbr1072_Fig6a.pdf
Rscript template_function_AllCellsCD47KO_Filtered_SO.R
mv Rplots.pdf AllCellsCD47KO_Filtered_SO.pdf
Rscript template_function_R04C12_DualLabel_Cd34_Ermap.R
mv Rplots.pdf R04C12_DualLabel_Cd34_Ermap.pdf
Rscript template_function_R04C12_DualLabel_Cd34_Klf1.R
mv Rplots.pdf R04C12_DualLabel_Cd34_Klf1.pdf
Rscript template_function_R04C14_Filtered_ViolinPlot_Fig4_AllGenes.R
mv Rplots.pdf R04C14_Filtered_ViolinPlot_Fig4_AllGenes.pdf 
Rscript template_function_R04C14_Filtered_ViolinPlot_Fig4_AllGenes_V86.R
mv Rplots.pdf R04C14_Filtered_ViolinPlot_Fig4_AllGenes_V86.pdf
Rscript template_function_R04C14_Filtered_ViolinPlot_Fig4_AllGenes_V89.R
mv Rplots.pdf R04C14_Filtered_ViolinPlot_Fig4_AllGenes_V89.pdf
Rscript template_function_R04C14_Filtered_ViolinPlot_Fig4_Kit.R
mv Rplots.pdf R04C14_Filtered_ViolinPlot_Fig4_Kit.pdf
Rscript template_function_R04C14_Filtered_ViolinPlot_Fig4_Mki67.R
mv Rplots.pdf R04C14_Filtered_ViolinPlot_Fig4_Mki67.pdf
Rscript template_function_R04C14_Filtered_ViolinPlot_Fig4_Ranbp2.R
mv Rplots.pdf R04C14_Filtered_ViolinPlot_Fig4_Ranbp2.pdf
Rscript template_function_R04C14_Filtered_ViolinPlot_Fig4_Xpo1.R
mv Rplots.pdf R04C14_Filtered_ViolinPlot_Fig4_Xpo1.pdf
Rscript template_function_RBCProg_Reclustered_SO.R
mv Rplots.pdf RBCProg_Reclustered_SO.pdf
Rscript template_function_ccbr1072_Fig3d1.R
mv Rplots.pdf ccbr1072_Fig3d1.pdf
Rscript template_function_ccbr1072_Fig3d2.R
mv Rplots.pdf ccbr1072_Fig3d2.pdf
Rscript template_function_ccbr1072_Fig5.R
mv Rplots.pdf ccbr1072_Fig5.pdf
Rscript template_function_R04C12Cd34neg_Filtered_SO.R
mv Rplots.pdf R04C12Cd34neg_Filtered_SO.pdf
Rscript template_function_R04C12Cd34pos_Filtered_SO.R
mv Rplots.pdf R04C12Cd34pos_Filtered_SO.pdf
Rscript template_function_R04C12_DualLabel_Cd34_Gata1.R
mv Rplots.pdf R04C12_DualLabel_Cd34_Gata1.pdf
Rscript template_function_R04C12_DualLabel_Mki67_Cd34.R
mv Rplots.pdf R04C12_DualLabel_Mki67_Cd34.pdf
Rscript template_function_R04C12_DualLabel_Mki67_Ermap.R
mv Rplots.pdf R04C12_DualLabel_Mki67_Ermap.pdf
Rscript template_function_R04C12_DualLabel_Mki67_Kit.R
mv Rplots.pdf R04C12_DualLabel_Mki67_Kit.pdf
Rscript template_function_R04C12_DualLabel_Mki67_Ly6a.R
mv Rplots.pdf R04C12_DualLabel_Mki67_Ly6a.pdf
Rscript template_function_R04C12_Filtered_DEG.R
Rscript template_function_R04C14Cd34neg_Filtered_SO.R
mv Rplots.pdf R04C14Cd34neg_Filtered_SO.pdf
Rscript template_function_R04C14Cd34pos_Filtered_SO.R
mv Rplots.pdf R04C14Cd34pos_Filtered_SO.pdf
Rscript template_function_R04C14_Filtered_DEG.R
Rscript template_function_ccbr1072_Fig6d.R
mv Rplots.pdf ccbr1072_Fig6d.pdf
Rscript template_function_R04C12Cd34neg_Filtered_SO2.R
mv Rplots.pdf R04C12Cd34neg_Filtered_SO2.pdf
Rscript template_function_R04C12Cd34pos_Filtered_SO2.R
mv Rplots.pdf R04C12Cd34pos_Filtered_SO2.pdf
Rscript template_function_R04C12_DEG_Volcano_CD47KOvsWT.R
Rscript template_function_R04C12_DEG_Volcano_TSP1KOvsWT.R
Rscript template_function_R04C12_DualLabel_Mki67_Klf1.R
mv Rplots.pdf R04C12_DualLabel_Mki67_Klf1.pdf
Rscript template_function_R04C14Cd34neg_Filtered_SO2.R
mv Rplots.pdf R04C14Cd34neg_Filtered_SO2.pdf
Rscript template_function_R04C14Cd34pos_Filtered_SO2.R
mv Rplots.pdf R04C14Cd34pos_Filtered_SO2.pdf
Rscript template_function_R04C14_DEG_Volcano_CD47KOvsWT_copied.R
Rscript template_function_R04C14_DEG_Volcano_TSP1KOvsWT_copied.R
Rscript template_function_RBCProg_ReclusteredCellTypes_SO.R
mv Rplots.pdf RBCProg_ReclusteredCellTypes_SO.pdf
Rscript template_function_ccbr1072_Fig7a.R
mv Rplots.pdf ccbr1072_Fig7a.pdf
Rscript template_function_ccbr1072_Fig7b.R
mv Rplots.pdf ccbr1072_Fig7b.pdf
Rscript template_function_ccbr1072_Fig7c.R
mv Rplots.pdf ccbr1072_Fig7c.pdf
Rscript template_function_ccbr1072_Fig7d.R
mv Rplots.pdf ccbr1072_Fig7d.pdf
Rscript template_function_R04C12DEG_CD47KOvsWT_GSEA.R
Rscript template_function_R04C12DEG_TSP1KOvsWT_GSEA.R
Rscript template_function_R04C12_DualLabel_Mki67_Epor.R
mv Rplots.pdf R04C12_DualLabel_Mki67_Epor.pdf
Rscript template_function_R04C14DEG_CD47KOvsWT_GSEA.R
Rscript template_function_R04C14DEG_TSP1KOvsWT_GSEA.R
Rscript template_function_ccbr1072_Fig6b.R
mv Rplots.pdf ccbr1072_Fig6b.pdf
Rscript template_function_ccbr1072_Fig6c.R
mv Rplots.pdf ccbr1072_Fig6c.pdf
Rscript template_function_R04C12Cd34neg_Filtered_DEG.R
Rscript template_function_R04C12Cd34neg_Filtered_DEG_CD47KOvsWT_Volcano.R
Rscript template_function_R04C12Cd34neg_Filtered_DEG_TSP1KOvsWT_Volcano.R
Rscript template_function_R04C12Cd34neg_TSP1KOvsWT_GSEA.R
Rscript template_function_R04C12Cd34pos_Filtered_DEG.R
Rscript template_function_R04C12Cd34pos_Filtered_DEG_CD47KOvsWT_Volcano.R
Rscript template_function_R04C12_DualLabel_Klf1_Ermap.R
mv Rplots.pdf R04C12_DualLabel_Klf1_Ermap.pdf
Rscript template_function_R04C12_DualLabel_Klf1_Gata1.R
mv Rplots.pdf R04C12_DualLabel_Klf1_Gata1.pdf
Rscript template_function_R04C14Cd34neg_Filtered_DEG.R
Rscript template_function_R04C14Cd34neg_Filtered_DEG_CD47KOvsWT_Volcano_copied.R
Rscript template_function_R04C14Cd34neg_Filtered_DEG_TSP1KOvsWT_Volcano_copied.R
Rscript template_function_R04C14Cd34neg_TSP1KOvsWT_GSEA.R
Rscript template_function_R04C14Cd34pos_Filtered_DEG.R
Rscript template_function_R04C14Cd34pos_Filtered_DEG_CD47KOvsWT_Volcano_copied.R
Rscript template_function_R04C14Cd34pos_Filtered_DEG_TSP1KOvsWT_Volcano_copied.R
Rscript template_function_R04C14Cd34pos_TSP1KOvsWT_GSEA.R
Rscript template_function_RBCProg_ReclusteredCellTypes_DEG_MouseRNAseq.R
Rscript template_function_RBCProg_ReclusteredCellTypes_DEG_TreatmentGroup.R
Rscript template_function_RBCProg_ReclusteredCellTypes_FilterEryth_SO.R
mv Rplots.pdf RBCProg_ReclusteredCellTypes_FilterEryth_SO.pdf
Rscript template_function_RBCProg_ReclusteredCellTypes_FilterTCells_SO.R
mv Rplots.pdf RBCProg_ReclusteredCellTypes_FilterTCells_SO.pdf
Rscript template_function_RBCProg_ReclusteredCellTypes_VolcanobyTreatment_CD47KOvsWT_copied.R
Rscript template_function_RBCProg_ReclusteredCellTypes_VolcanobyTreatment_TSP1KOvsWT_copied.R
Rscript template_function_ccbr1072_SuppFig7b2.R
Rscript template_function_R04C12Cd34neg_CD47KOvsWT_GSEA.R
Rscript template_function_R04C12Cd34pos_CD47KOvsWT_GSEA.R
Rscript template_function_R04C12_DualLabel_Ermap_Gata1.R
mv Rplots.pdf R04C12_DualLabel_Ermap_Gata1.pdf
Rscript template_function_R04C12_DualLabel_Kit_Ermap.R
mv Rplots.pdf R04C12_DualLabel_Kit_Ermap.pdf
Rscript template_function_R04C12_DualLabel_Kit_Klf1.R
mv Rplots.pdf R04C12_DualLabel_Kit_Klf1.pdf
Rscript template_function_R04C12_DualLabel_Ly6a_Ermap.R
mv Rplots.pdf R04C12_DualLabel_Ly6a_Ermap.pdf
Rscript template_function_R04C12_DualLabel_Ly6a_Klf1.R
mv Rplots.pdf R04C12_DualLabel_Ly6a_Klf1.pdf
Rscript template_function_R04C14Cd34neg_CD47KOvsWT_GSEA.R
Rscript template_function_R04C14Cd34pos_CD47KOvsWT_GSEA.R
Rscript template_function_RBCProgReclustDEG_CD47KOvsWT_GSEAPreranked.R
Rscript template_function_RBCProgReclustDEG_ErythVsTcells_GSEAPreranked.R
Rscript template_function_RBCProgReclustDEG_TSP1KOvsWT_GSEAPreranked.R
Rscript template_function_RBCProg_ReclusteredCellTypes_FilterEryth_DEG_Treatment.R
Rscript template_function_RBCProg_ReclusteredCellTypes_FilterEryth_DEG_Treatment_Volcano_CD47KOvsWT_copied.R
Rscript template_function_RBCProg_ReclusteredCellTypes_FilterEryth_DEG_Treatment_Volcano_TSP1KOvsWT_copied.R
Rscript template_function_RBCProg_ReclusteredCellTypes_FilterTCells_DEG_Treatment.R
Rscript template_function_RBCProg_ReclusteredCellTypes_FilterTCells_DEG_Treatment_Volcano_CD47KOvsWT_copied.R
Rscript template_function_RBCProg_ReclusteredCellTypes_FilterTCells_DEG_Treatment_Volcano_TSP1KOvsWT_copied.R
Rscript template_function_RBCProgReclustFilterErythDEG_CD47KOvsWT_GSEAPreranked.R
Rscript template_function_RBCProgReclustFilterErythDEG_TSP1KOvsWT_GSEAPreranked.R
Rscript template_function_RBCProgReclustFilterTcellsDEG_CD47KOvsWT_GSEAPreranked.R
Rscript template_function_RBCProgReclustFilterTcellsDEG_TSP1KOvsWT_GSEAPreranked.R
#source("workbook_start_globals.R")
